import { Product } from '@/types/product'
import { Category } from '@/types/category'

const now = new Date().toISOString()

export const mockCategories: Category[] = [
  {
    id: 'cat-fresh-produce',
    name: 'Fresh Produce',
    slug: 'fresh-produce',
    description: 'Farm-fresh fruits and vegetables',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80',
    isActive: true,
    sortOrder: 1,
    productCount: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'cat-dairy',
    name: 'Dairy & Eggs',
    slug: 'dairy',
    description: 'Milk, cheese, yogurt and eggs',
    image: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=800&q=80',
    isActive: true,
    sortOrder: 2,
    productCount: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'cat-bakery',
    name: 'Bakery',
    slug: 'bakery',
    description: 'Freshly baked bread and pastries',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80',
    isActive: true,
    sortOrder: 3,
    productCount: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'cat-meat',
    name: 'Meat & Seafood',
    slug: 'meat',
    description: 'Quality cuts and fresh seafood',
    image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800&q=80',
    isActive: true,
    sortOrder: 4,
    productCount: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'cat-pantry',
    name: 'Pantry Essentials',
    slug: 'pantry',
    description: 'Staples for every kitchen',
    image: 'https://images.unsplash.com/photo-1584473457406-6240486418e9?w=800&q=80',
    isActive: true,
    sortOrder: 5,
    productCount: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'cat-beverages',
    name: 'Beverages',
    slug: 'beverages',
    description: 'Refreshing drinks and juices',
    image: 'https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=800&q=80',
    isActive: true,
    sortOrder: 6,
    productCount: 3,
    createdAt: now,
    updatedAt: now,
  },
]

export const mockProducts: Product[] = [
  // Fresh Produce
  {
    id: 'p-bananas',
    name: 'Organic Bananas',
    description: 'Sweet and ripe organic bananas, perfect for snacks and smoothies.',
    price: 1.49,
    category: 'fresh-produce',
    stock: 120,
    images: ['https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=800&q=80'],
    status: 'active',
    sku: 'FP-BAN-001',
    tags: ['organic', 'fruit'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'p-apples',
    name: 'Red Apples (1kg)',
    description: 'Crisp and juicy red apples, hand-picked from local orchards.',
    price: 3.29,
    category: 'fresh-produce',
    stock: 80,
    images: ['https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=800&q=80'],
    status: 'active',
    sku: 'FP-APP-001',
    tags: ['fruit'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'p-tomatoes',
    name: 'Vine Tomatoes',
    description: 'Fresh vine-ripened tomatoes bursting with flavor.',
    price: 2.49,
    category: 'fresh-produce',
    stock: 60,
    images: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&q=80'],
    status: 'active',
    sku: 'FP-TOM-001',
    tags: ['vegetable'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'p-avocado',
    name: 'Hass Avocados',
    description: 'Creamy Hass avocados, perfect for toast, salads, and guacamole.',
    price: 1.99,
    category: 'fresh-produce',
    stock: 50,
    images: ['https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=800&q=80'],
    status: 'active',
    sku: 'FP-AVO-001',
    tags: ['fruit'],
    createdAt: now,
    updatedAt: now,
  },
  // Dairy
  {
    id: 'p-milk',
    name: 'Whole Milk (1L)',
    description: 'Farm fresh whole milk, rich in calcium and vitamins.',
    price: 1.89,
    category: 'dairy',
    stock: 100,
    images: ['https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800&q=80'],
    status: 'active',
    sku: 'DR-MLK-001',
    tags: ['dairy'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'p-eggs',
    name: 'Free-Range Eggs (12)',
    description: 'A dozen free-range eggs from happy hens.',
    price: 4.49,
    category: 'dairy',
    stock: 70,
    images: ['https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=800&q=80'],
    status: 'active',
    sku: 'DR-EGG-001',
    tags: ['eggs'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'p-cheese',
    name: 'Aged Cheddar Cheese',
    description: 'Sharp and creamy aged cheddar, aged for 12 months.',
    price: 6.99,
    category: 'dairy',
    stock: 40,
    images: ['https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=800&q=80'],
    status: 'active',
    sku: 'DR-CHE-001',
    tags: ['cheese'],
    createdAt: now,
    updatedAt: now,
  },
  // Bakery
  {
    id: 'p-sourdough',
    name: 'Artisan Sourdough Loaf',
    description: 'Handcrafted sourdough with a crisp crust and chewy interior.',
    price: 5.49,
    category: 'bakery',
    stock: 30,
    images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80'],
    status: 'active',
    sku: 'BK-SOU-001',
    tags: ['bread'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'p-croissant',
    name: 'Butter Croissants (4 pack)',
    description: 'Flaky, buttery croissants baked fresh every morning.',
    price: 7.99,
    category: 'bakery',
    stock: 25,
    images: ['https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800&q=80'],
    status: 'active',
    sku: 'BK-CRO-001',
    tags: ['pastry'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'p-bagels',
    name: 'Everything Bagels (6 pack)',
    description: 'Chewy bagels topped with sesame, poppy, garlic and onion.',
    price: 4.99,
    category: 'bakery',
    stock: 35,
    images: ['https://images.unsplash.com/photo-1612277795421-9bc7706a4a34?w=800&q=80'],
    status: 'active',
    sku: 'BK-BAG-001',
    tags: ['bagel'],
    createdAt: now,
    updatedAt: now,
  },
  // Meat
  {
    id: 'p-chicken',
    name: 'Free-Range Chicken Breast',
    description: 'Boneless, skinless chicken breast from free-range farms.',
    price: 8.99,
    category: 'meat',
    stock: 40,
    images: ['https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=800&q=80'],
    status: 'active',
    sku: 'MT-CHK-001',
    tags: ['poultry'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'p-beef',
    name: 'Premium Beef Steak',
    description: 'Tender, grass-fed beef steak, perfect for grilling.',
    price: 14.99,
    category: 'meat',
    stock: 20,
    images: ['https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800&q=80'],
    status: 'active',
    sku: 'MT-BEF-001',
    tags: ['beef'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'p-salmon',
    name: 'Atlantic Salmon Fillet',
    description: 'Fresh Atlantic salmon, rich in omega-3 fatty acids.',
    price: 12.49,
    category: 'meat',
    stock: 25,
    images: ['https://images.unsplash.com/photo-1599084993091-1cb5c0721cc6?w=800&q=80'],
    status: 'active',
    sku: 'MT-SAL-001',
    tags: ['seafood'],
    createdAt: now,
    updatedAt: now,
  },
  // Pantry
  {
    id: 'p-pasta',
    name: 'Italian Pasta (500g)',
    description: 'Authentic Italian pasta made with durum wheat semolina.',
    price: 2.29,
    category: 'pantry',
    stock: 90,
    images: ['https://images.unsplash.com/photo-1551462147-37885acc36f1?w=800&q=80'],
    status: 'active',
    sku: 'PT-PAS-001',
    tags: ['pasta'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'p-olive-oil',
    name: 'Extra Virgin Olive Oil',
    description: 'Cold-pressed extra virgin olive oil from Mediterranean groves.',
    price: 9.99,
    category: 'pantry',
    stock: 50,
    images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&q=80'],
    status: 'active',
    sku: 'PT-OLO-001',
    tags: ['oil'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'p-rice',
    name: 'Basmati Rice (2kg)',
    description: 'Long-grain aromatic basmati rice from the foothills of the Himalayas.',
    price: 6.49,
    category: 'pantry',
    stock: 60,
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&q=80'],
    status: 'active',
    sku: 'PT-RIC-001',
    tags: ['grain'],
    createdAt: now,
    updatedAt: now,
  },
  // Beverages
  {
    id: 'p-orange-juice',
    name: 'Fresh Orange Juice (1L)',
    description: 'Freshly squeezed orange juice with no added sugar.',
    price: 4.29,
    category: 'beverages',
    stock: 60,
    images: ['https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=800&q=80'],
    status: 'active',
    sku: 'BV-OJ-001',
    tags: ['juice'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'p-coffee',
    name: 'Premium Coffee Beans (500g)',
    description: 'Single-origin arabica coffee beans, medium roast.',
    price: 11.99,
    category: 'beverages',
    stock: 45,
    images: ['https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&q=80'],
    status: 'active',
    sku: 'BV-COF-001',
    tags: ['coffee'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'p-sparkling-water',
    name: 'Sparkling Water (6 pack)',
    description: 'Refreshing sparkling water with a hint of natural lime.',
    price: 5.99,
    category: 'beverages',
    stock: 80,
    images: ['https://images.unsplash.com/photo-1605193517402-2e02d29be7d3?w=800&q=80'],
    status: 'active',
    sku: 'BV-SPW-001',
    tags: ['water'],
    createdAt: now,
    updatedAt: now,
  },
]

export function getMockProducts(filters?: { category?: string; search?: string }): Product[] {
  let list = [...mockProducts]
  if (filters?.category) {
    list = list.filter(p => p.category === filters.category)
  }
  if (filters?.search) {
    const q = filters.search.toLowerCase()
    list = list.filter(p => p.name.toLowerCase().includes(q) || p.description.toLowerCase().includes(q))
  }
  return list
}
